### ISSUE TITLE
config ibus-setup error

### ISSUE THREAD

**Issue by csdlmysql** [BambooEngine/ibus-bamboo#40]
**Mô tả lỗi**
from gi.repository import GLib
module gi not found.
hey bro, /usr/share/ibus/setup/main.py file write python2 but run it with python3 @@. please modify python3 to python2 in /usr/bin/ibus-setup. goodluck man.

**Comment by ndgnuh** [comment]
I don't know what you are talking about. There's no `/usr/share/ibus/setup/main.py` file in this package, nor does the source code it self be written in `python`.

The destdir `tree` result:
```sh
└── usr
    ├── lib
    │   └── ibus-engine-bamboo
    └── share
        ├── ibus
        │   └── component
        │       └── bamboo.xml
        └── ibus-bamboo
            ├── data
            │   ├── COPYING.emojione
            │   ├── emojione.json
            │   ├── LICENSE.vietnamese.cm.dict
            │   ├── macro.tpl.txt
            │   └── vietnamese.cm.dict
            └── viet-on.png
```

Also, if a script uses wrong version of python, it might be because that you haven't configured your `python` alternative. Consult the wiki page of the package manager that you are using for more info.

**Comment by luongthanhlam** [comment]
This's issue of ibus, not ibus-bamboo. See https://github.com/ibus/ibus/issues/2086 for more information.
