### ISSUE TITLE
There is no Debian 12 Release for Ibus-Bamboo

### ISSUE THREAD

**Issue by libraryoflilcarp87** [BambooEngine/ibus-bamboo#465]
_**Note:**_
Debian 12 users need to install  [python3-launchpadlib] to be able to use add-apt-repository after, by running this line:
`sudo apt-get install python3-launchpadlib`

After that, I've tried to run:
`sudo add-apt-repository ppa:bamboo-engine/ibus-bamboo`

Then got the 404 error saying there is no repository for such file (please see the picture)

![Screenshot_20240203_121646](https://github.com/BambooEngine/ibus-bamboo/assets/106779551/dbb1b8e9-5177-4d43-ae2a-b033f0dff2bc)

**_Update:_**
I've researched and use the following advice and still have the same trouble
![Screenshot_20240203_123833](https://github.com/BambooEngine/ibus-bamboo/assets/106779551/3fbb733e-cb60-4639-8f3e-04b411034b51)
 

How could we install this program if there is no support (no release file), please help! 

Thanks in advanced!

**Comment by goatastronaut0212** [comment]
I don't think it is a good idea when you use Debian system and mix Ubuntu packages. Debian have a section for that and it will explain why and you should read [it](https://wiki.debian.org/DontBreakDebian)

Beside, you should try remove Ubuntu apt repository in `/etc/apt/sources.list.d/` before you run `apt update` again.

I still think follow the instructions in this [link](https://software.opensuse.org//download.html?project=home%3Alamlng&package=ibus-bamboo) seem helpful since the last time I use Debian.

**Comment by luongthanhlam** [comment]
Yup, I'll close it now. Thanks @RepentantKnight121 !
