### ISSUE TITLE
[Feature Request] Support for Fedora 41

### ISSUE THREAD

**Issue by doankimhuy-it** [BambooEngine/ibus-bamboo#546]
Fedora 41 is out for nearly a month, could you please add support for it?
Thank you.

**Comment by goatastronaut0212** [comment]
@doankimhuy-it I would prefer to have one in Fedora official packages and someone may have to do it.

I don't actually own luongthanhlam OBS to modify or change things over there and I don't intend to do it. Beside, keeping a separate repo instead of submit package to Fedora community is quite a fragment solution to open source community.

**Comment by luongthanhlam** [comment]
Support for Fedora 41 has already been added!

**Comment by doankimhuy-it** [comment]
Thank you @luongthanhlam for your quick response.
I guess you guys should have a ticket to ask for volunteers maintaining this package in official fedora repo. This would be beneficial in the long run. I have no experience on this, so, sorry.
If you want to reuse this ticket, feel free to keep it open, otherwise you can close it. Thank you.

**Comment by goatastronaut0212** [comment]
Trong lúc mình search Bugzilla của Fedora xem ra có vẻ như fujiwara (nhà phát triển của Ibus cũng là Red Hat developer) đã để mắt tới ibus-bamboo. Có thể trong tương lai họ sẽ đem nó lên. Hên quá chúng ta có lẽ không cần phải làm nhưng mà mình không biết có thể giúp được gì không nữa

https://bugzilla.redhat.com/show_bug.cgi?id=2298104
